inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - tasks/*.rake
    - Guardfile
    - Rakefile
  Exclude:
    - gem/**/*
    - puppet/**/*
    - vendor/bundle/**/*

Metrics/AbcSize:
  Max: 20
  Exclude:
  - lib/nsidc_open_search/dataset_osdd.rb

Metrics/ClassLength:
  Max: 125

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
  Exclude:
  - lib/nsidc_open_search/dataset_osdd.rb

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Semicolon:
  Enabled: false
