AllCops:
  Include:
    - tasks/*.rake
    - Guardfile
    - Rakefile
    - '**/*.builder'
  Exclude:
    - gem/**/*
    - puppet/**/*
    - vendor/bundle/**/*
  NewCops: enable

Layout/LineLength:
  Max: 100

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 20
  Exclude:
  - lib/nsidc_open_search/dataset_osdd.rb

Metrics/ClassLength:
  Max: 125

Metrics/MethodLength:
  Max: 15
  Exclude:
  - lib/nsidc_open_search/dataset_osdd.rb

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Naming/MethodName:
  Exclude:
  - lib/nsidc_open_search/dataset/search/definitions/definition.rb # OpenSearch uses camelCase
