:development:
  :enricher_thread_count: 5
  :relative_url_root: /
  :solr_url: http://dev.search-solr.USERNAME.dev.int.nsidc.org:8983/solr/nsidc_oai
  :solr_auto_suggest_url: http://dev.search-solr.USERNAME.dev.int.nsidc.org:8983/solr/auto_suggest

:common:
  :enricher_thread_count: 5
  :relative_url_root: /api/dataset/2
  :port: '10680'
  :num_workers: 5
  :pidfile: /var/run/puma/search_services.pid
  :state_path: /var/run/puma/search_services.state
  :std_err_log: /var/log/search_services.stderr.log
  :std_out_log: /var/log/search_services.stdout.log

:integration:
  :solr_url: http://integration.search-solr.apps.int.nsidc.org:8983/solr/nsidc_oai
  :solr_auto_suggest_url: http://integration.search-solr.apps.int.nsidc.org:8983/solr/auto_suggest

:qa:
  :solr_url: http://qa.search-solr.apps.int.nsidc.org:8983/solr/nsidc_oai
  :solr_auto_suggest_url: http://qa.search-solr.apps.int.nsidc.org:8983/solr/auto_suggest

:staging:
  :solr_url: http://staging.search-solr.apps.int.nsidc.org:8983/solr/nsidc_oai
  :solr_auto_suggest_url: http://staging.search-solr.apps.int.nsidc.org:8983/solr/auto_suggest

:production:
  :solr_url: http://search-solr.apps.int.nsidc.org:8983/solr/nsidc_oai
  :solr_auto_suggest_url: http://search-solr.apps.int.nsidc.org:8983/solr/auto_suggest