:development:
  :enricher_thread_count: 5
  :relative_url_root: /
  :solr_url: https://dev.search-solr.USERNAME.dev.int.nsidc.org/solr/nsidc_oai
  :solr_auto_suggest_url: https://dev.search-solr.USERNAME.dev.int.nsidc.org/solr/auto_suggest
# You can use the below for testing if you don't want to set up a dev machine
#  :solr_url: https://integration.search-solr.apps.int.nsidc.org/solr/nsidc_oai
#  :solr_auto_suggest_url: https://integration.search-solr.apps.int.nsidc.org/solr/auto_suggest

:common:
  :enricher_thread_count: 5
  :relative_url_root: /api/dataset/2
  :port: '10680'
  :num_workers: 5
  :pidfile: /var/run/puma/search_services.pid
  :state_path: /var/run/puma/search_services.state
  :std_err_log: /var/log/search_services.stderr.log
  :std_out_log: /var/log/search_services.stdout.log

:integration:
  :solr_url: https://integration.search-solr.apps.int.nsidc.org/solr/nsidc_oai
  :solr_auto_suggest_url: https://integration.search-solr.apps.int.nsidc.org/solr/auto_suggest

:qa:
  :solr_url: https://qa.search-solr.apps.int.nsidc.org/solr/nsidc_oai
  :solr_auto_suggest_url: https://qa.search-solr.apps.int.nsidc.org/solr/auto_suggest

:staging:
  :solr_url: https://staging.search-solr.apps.int.nsidc.org/solr/nsidc_oai
  :solr_auto_suggest_url: https://staging.search-solr.apps.int.nsidc.org/solr/auto_suggest

:production:
  :solr_url: https://search-solr.apps.int.nsidc.org/solr/nsidc_oai
  :solr_auto_suggest_url: https://search-solr.apps.int.nsidc.org/solr/auto_suggest

