NSIDC:
  query_fields:
    - authoritative_id
    - title
    - parameters
    - summary
    - topics
    - keywords
    - platforms
    - sensors
    - normalized_authoritative_id
    - authors
  facet_defaults:
    facet.mincount: 1
    facet.sort: index
    facet.limit: -1
  facets:
    -
      name: facet_parameter
    -
      name: facet_spatial_coverage
      solr:
        mincount: 0
        sort: count
    -
      name: facet_spatial_resolution
    -
      name: facet_temporal_duration
      sort: defined_sort
      sort_order:
        - '< 1 year'
        - '1 - 4 years'
        - '5 - 9 years'
        - '10+ years'
        - 'Not specified'
    -
      name: facet_temporal_resolution
    -
      name: facet_format
      sort: not_specified_last
    -
      name: facet_sensor
      sort: short_name_sort
    -
      name: facet_sponsored_program
      sort: short_name_sort

  query_field_boosts:
    title: 15
    parameters: 3
    keywords: 3
    sensors: 2
    platforms: 2
    summary: 5
    normalized_authoritative_id: 100
  phrase_fields:
    - title
    - parameters
    - summary
    - keywords
  phrase_field_boosts:
    title: 25
    summary: 25
    parameters: 5
    keywords: 5
  phrase_slop: 1
  boost_query: brokered:false^100 published_date:[NOW-2YEARS/DAY TO NOW/DAY]^15 #boost non-brokered datasets and datasets published in the last 2 years
  boost: product(popularity,query({!type=edismax qf=$qf pf=$pf ps=$ps bq=$bq bf=sum(1,product(tan(div(popularity,8)),50))^55 v=$q boost=})) #scale documents by how well they satisfy the query and their popularity
