NSIDC:
  query_fields:
    - title
    - parameters
    - summary
    - topics
    - keywords
    - platforms
    - sensors
    - normalized_authoritative_id
    - authors
  facet_defaults:
    facet.mincount: 1
    facet.sort: index
    facet.limit: -1
  facets:
    -
      name: facet_parameter
    -
      name: facet_spatial_coverage
    -
      name: facet_spatial_resolution
      sort: defined_sort
      sort_order:
        - '0 - 500 m'
        - '501 m - 1 km'
        - '2 - 5 km'
        - '6 - 15 km'
        - '16 - 30 km'
        - '>30 km'
        - 'Not specified'
    -
      name: facet_temporal_duration
      sort: defined_sort
      sort_order:
        - '< 1 year'
        - '1+ years'
        - '5+ years'
        - '10+ years'
        - 'Not specified'
    -
      name: facet_temporal_resolution
      sort: defined_sort
      sort_order:
        - 'Subhourly'
        - 'Hourly'
        - 'Subdaily'
        - 'Daily'
        - 'Weekly'
        - 'Submonthly'
        - 'Monthly'
        - 'Subyearly'
        - 'Yearly'
        - 'Multiyearly'
        - 'Not specified'
    -
      name: facet_format
      sort: not_specified_last
    -
      name: facet_sensor
      sort: short_name_sort
    -
      name: facet_sponsored_program
      sort: short_name_sort

  query_field_boosts:
    title: 15
    parameters: 3
    keywords: 3
    sensors: 2
    platforms: 2
    summary: 5
    normalized_authoritative_id: 100
  phrase_fields:
    - title
    - parameters
    - summary
    - keywords
  phrase_field_boosts:
    title: 25
    summary: 25
    parameters: 5
    keywords: 5
  phrase_slop: 1
  boost_query: brokered:false^100 published_date:[NOW-2YEARS/DAY TO NOW/DAY]^15 #boost non-brokered datasets and datasets published in the last 2 years
  boost: product(popularity,query({!type=edismax qf=$qf pf=$pf ps=$ps bq=$bq bf=sum(1,product(tan(div(popularity,8)),50))^55 v=$q boost=})) #scale documents by how well they satisfy the query and their popularity
ADE:
  query_fields:
    - title
    - summary
    - keywords
    - parameters
    - authors
  facet_defaults:
    facet.sort: count
    facet.limit: -1
  facets:
    -
      name: facet_temporal_duration
      sort: defined_sort
      sort_order:
        - '< 1 year'
        - '1+ years'
        - '5+ years'
        - '10+ years'
        - 'Not specified'
    -
      name: facet_spatial_scope
      sort: defined_sort
      sort_order:
        - 'Less than 1 degree of latitude change | Local'
        - 'Between 1 and 170 degrees of latitude change | Regional'
        - 'Coverage from over 85 degrees North to -85 degrees South | Global'
    -
      name: facet_data_center
      values:
        - 'National Snow and Ice Data Center | NSIDC'
        - 'NSF Arctic Data Center | NSF ADC'
        - 'UCAR/NCAR - Earth Observing Laboratory | UCAR/NCAR EOL'
        - 'UCAR/NCAR Research Data Archive | UCAR/NCAR RDA'
        - 'NOAA National Oceanographic Data Center | NOAA NODC'
        - 'Norwegian Meteorological Institute | Met.no'
        - 'NASA Earth Observing System (EOS) Clearing House | NASA ECHO'
        - 'International Council for the Exploration of the Sea | ICES'
  query_field_boosts:
    title: 40
    summary: 20
    keywords: 4
    parameters: 4
  phrase_fields:
    - title
    - summary
    - keywords
    - parameters
    - sortKeys
  phrase_field_boosts:
    title: 40
    summary: 20
    keywords: 4
    parameters: 4
  phrase_slop: 2
  boost_query: published_date:[NOW-2YEARS/DAY TO NOW/DAY]^10 #boost non-brokered datasets and datasets published in the last 2 years
  sort: score,,0
