NSIDC:
  query_fields:
    - title
    - parameters
    - summary
    - keywords
    - platforms
    - sensors
    - normalized_authoritative_id
    - authors
  facet_defaults:
    facet.mincount: 1
    facet.sort: index
    facet.limit: -1
  facets:
    -
      name: facet_storage_location
    -
      name: facet_spatial_coverage
    -
      name: facet_parameter

    # Metadata for spatial and temporal resolution.
    # To re-instate the facet for spatial resolution, uncomment the following
    # lines and add additional sort_order options as needed.
    # -
     # name: facet_spatial_resolution
     # sort: defined_sort
     # sort_order:
     #  - '0 - 500 m'
     #  - '501 m - 1 km'
     #  etc.
    -
      name: facet_temporal_duration
      sort: defined_sort
      sort_order:
        - '< 1 year'
        - '1+ years'
        - '5+ years'
        - '10+ years'
        - 'Not specified'
    #
    # To re-instate the facet for temporal resolution, uncomment the following
    # lines and add additional sort_order options as needed.
    # -
     # name: facet_temporal_resolution
     # sort: defined_sort
     # sort_order:
      #  - 'Subhourly'
      #  - 'Hourly'
      #  - 'Subdaily'
      #  etc.
    -
      name: facet_format
      sort: not_specified_last
    -
      name: facet_sensor
      sort: short_name_sort
    -
      name: facet_sponsored_program
      sort: short_name_sort

  query_field_boosts:
    title: 15
    parameters: 3
    sensors: 2
    platforms: 2
    summary: 5
    normalized_authoritative_id: 5
  phrase_fields:
    - title
    - parameters
    - summary
    - keywords
  phrase_field_boosts:
    title: 25
    summary: 25
    parameters: 5
  phrase_slop: 1
  boost_query: brokered:false^100 published_date:[NOW-2YEARS/DAY TO NOW/DAY]^15 #boost non-brokered datasets and datasets published in the last 2 years
  boost: product(popularity,query({!type=edismax qf=$qf pf=$pf ps=$ps bq=$bq bf=sum(1,product(tan(div(popularity,8)),50))^55 v=$q boost=})) #scale documents by how well they satisfy the query and their popularity
